I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script5_6.rpy", line 159, in script
    o "ขอบคุณมากเลยนะหนู ถ้าไม่มีหนู แว่นยายก็คงแตกไปแล้ว"
Exception: Sayer 'o' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script5_6.rpy", line 159, in script
    o "ขอบคุณมากเลยนะหนู ถ้าไม่มีหนู แว่นยายก็คงแตกไปแล้ว"
  File "D:\renpy-8.0.3-sdk\renpy-8.0.3-sdk\renpy\ast.py", line 881, in execute
    who = eval_who(self.who, self.who_fast)
  File "D:\renpy-8.0.3-sdk\renpy-8.0.3-sdk\renpy\ast.py", line 774, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'o' is not defined.

Windows-10-10.0.19045 AMD64
Ren'Py 8.0.3.22090809
Cafe_au_lait 1.0
Mon Jun  5 04:19:00 2023
