I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script6_5.rpy", line 13, in script
    m "ทาคากิ วันนี้อย่าลืมลงไปกินข้าวนะ"
Exception: Sayer 'm' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script6_5.rpy", line 13, in script
    m "ทาคากิ วันนี้อย่าลืมลงไปกินข้าวนะ"
  File "D:\renpy-8.0.3-sdk\renpy-8.0.3-sdk\renpy\ast.py", line 881, in execute
    who = eval_who(self.who, self.who_fast)
  File "D:\renpy-8.0.3-sdk\renpy-8.0.3-sdk\renpy\ast.py", line 774, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'm' is not defined.

Windows-10-10.0.19045 AMD64
Ren'Py 8.0.3.22090809
Cafe_au_lait 1.0
Fri Jun  9 19:13:09 2023
