I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script3.rpy", line 261, in script
    show Eimi_Eimi_0.0
Exception: Image 'Eimi_Eimi_0' does not accept attributes '.0'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script3.rpy", line 261, in script
    show Eimi_Eimi_0.0
  File "D:\renpy-8.0.1-sdk\renpy\ast.py", line 1408, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "D:\renpy-8.0.1-sdk\renpy\ast.py", line 1371, in show_imspec
    renpy.config.show(name,
  File "D:\renpy-8.0.1-sdk\renpy\exports.py", line 686, in show
    if not base.find_target() and renpy.config.missing_show:
  File "D:\renpy-8.0.1-sdk\renpy\display\image.py", line 413, in find_target
    self.target = target._duplicate(a)
  File "D:\renpy-8.0.1-sdk\renpy\display\transform.py", line 881, in _duplicate
    args.extraneous()
  File "D:\renpy-8.0.1-sdk\renpy\display\core.py", line 265, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'Eimi_Eimi_0' does not accept attributes '.0'.

Windows-10-10.0.19042 AMD64
Ren'Py 8.0.1.22070801
Cafe_au_lait 1.0
Wed Mar 15 02:20:30 2023
