I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script4_3b.rpy", line 57, in script
    show oppai_zoom02  Dissolve(1.0)
Exception: Image 'oppai_zoom02' does not accept attributes 'Dissolve (1.0)'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script4_3b.rpy", line 57, in script
    show oppai_zoom02  Dissolve(1.0)
  File "D:\renpy-8.0.3-sdk\renpy-8.0.3-sdk\renpy\ast.py", line 1408, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "D:\renpy-8.0.3-sdk\renpy-8.0.3-sdk\renpy\ast.py", line 1371, in show_imspec
    renpy.config.show(name,
  File "D:\renpy-8.0.3-sdk\renpy-8.0.3-sdk\renpy\exports.py", line 686, in show
    if not base.find_target() and renpy.config.missing_show:
  File "D:\renpy-8.0.3-sdk\renpy-8.0.3-sdk\renpy\display\image.py", line 414, in find_target
    self.target = target._duplicate(a)
  File "D:\renpy-8.0.3-sdk\renpy-8.0.3-sdk\renpy\display\core.py", line 397, in _duplicate
    args.extraneous()
  File "D:\renpy-8.0.3-sdk\renpy-8.0.3-sdk\renpy\display\core.py", line 265, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'oppai_zoom02' does not accept attributes 'Dissolve (1.0)'.

Windows-10-10.0.19045 AMD64
Ren'Py 8.0.3.22090809
Cafe_au_lait 1.0
Wed Jun 28 23:09:12 2023
